name: Docker Image CI

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"

jobs:
  build-tags:
    # Build and push the image with the tag name
    uses: soulsbros/CICD-template/.github/workflows/docker-build.yml@main
    if: github.ref_type == 'tag'
    with:
      image-name: steeven9/plap:${{ github.ref_name }}
      push: true
      # runner: self-hosted
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-branches:
    # Build all branches but push only in main
    uses: soulsbros/CICD-template/.github/workflows/docker-build.yml@main
    if: github.ref_type == 'branch'
    with:
      image-name: steeven9/plap:latest
      push: ${{ github.ref_name == 'main' }}
      ping_webhook: false
      # runner: self-hosted
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      # WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
